name: lint
on: [push, pull_request]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Lint YAML (non-blocking)
        run: |
          yamllint -d '{extends: default, rules: {line-length: {max: 140}}}' . || true
